services:
  web:
    build:
      dockerfile: ./prod.Dockerfile
    ports:
      - '4833:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/custom/.env
      - ./src:/custom/src
      - ./public:/custom/public
      - ./config:/custom/config
      - ./config.js:/custom/config.js
      - ./theme.js:/custom/theme.js
    command:
      - /bin/sh
      - -c
      - |
        npm install react-leaflet@4.2.1 @changey/react-leaflet-markercluster@4.0.0-rc1 leaflet-gesture-handling@1.2.2 react-tagcloud@2.3.3
        cp -r /custom/. /usr/src/app/
        npm run build
        npm start
    restart: unless-stopped
  mongo:
    restart: unless-stopped
  imaginary:
    restart: unless-stopped
  redis:
    restart: unless-stopped
