version: '3'
services:
  web:
    container_name: odeuropa-explorer_web
    build:
      context: https://github.com/D2KLab/explorer.git
    args:
       MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
  mongo:
    container_name: odeuropa-explorer_mongo
    image: mongo
    volumes:
      - mongo:/data/db
  imaginary:
    container_name: odeuropa-explorer_imaginary
    image: h2non/imaginary:latest
    volumes:
      - images:/mnt/data
    environment:
      PORT: 9000
    command: -enable-url-source -mount /mnt/data -allowed-origins ${IMAGINARY_ALLOWED_ORIGINS} -http-cache-ttl 31556926
    ports:
      - '9000:9000'
  redis:
    container_name: odeuropa-explorer_redis
    image: redis
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "4gb", "--maxmemory-policy", "allkeys-lru"]
volumes:
  mongo: {}
  images: {}
